### PR TITLE
JSON -> CSV conversion script for weather data files

### PR DESCRIPTION
**Pull request by spencer-carver**
Looking for feedback on output format for each column in the CSV

Specific questions:
1. do we care about the column order?
2. should units be included in the rows, or just raw values (and if the latter, where do we want units?)
3. are there any columns we don't want?

Sample csv output:
image

I assume we just want the `value` entry in the cell?

### CODE REVIEW

**Comment by dealom** [comment]
1. I don't think so.
2. Just raw values, units can be labeled on the visualizations
3. Maybe remove columns that have over 20%? or so nulls. For example, I think heatindex column has like 99% nulls so that can be removed.

**Comment by palakhjude** [comment]
1. I think column order should not matter too much, so long as the headers are consistent across everything, so then the pandas dataframe will use those headers.

2. I think having the raw value is better. For units, maybe another column, (with "_units") not too sure if that's the best way.

3. Can you list all the available columns?

**Comment by spencer-carver** [comment]
> 3. Can you list all the available columns?

```
            @id
            type
            elevation
            station
            timestamp
            rawMessage
            textDescription
            icon
            presentWeather
            temperature
            dewPoint
            windDirection
            windSpeed
            windGust
            barometricPressure
            seaLevelPressure
            visibility
            maxTemperatureLast24Hours
            minTemperatureLast24Hours
            precipitationLastHour
            precipitationLast3Hours
            precipitationLast6Hours
            relativeHumidity
            windChill
            heatIndex
            cloudLayers
```
There's a bit that is repetitive, so I think picking the one we like the best for modeling purposes (e.g. rain last 1/3/6 hours) makes sense

**Comment by hiwett18** [comment]
1. yes I agree, column order should not matter
2. I would just include the numerical values without units for now
3. Will you list the column names please

**Comment by hiwett18** [comment]
3. do we need id, icon, text description, raw_message?

**Comment by spencer-carver** [comment]
> 3. do we need id, icon, text description, raw_message?

Definitely not for modeling, but perhaps icon / description might be useful on the visualization. I can strip for now and easily add back later

**Comment by palakhjude** [comment]
Or you can leave the values in this output csv and we will drop the columns we don't need for modeling?

**Comment by hiwett18** [comment]
Correcting my previous message, we also need raw_message, text description

**Review by palakhjude — APPROVED** [review]
lgtm

**Pull request merged**
